
    # renovate: datasource=gitlab-tags depName=gitlab-com/gl-infra/common-ci-tasks versioning=semver registryUrl=gitlab.com
    GITLAB_COMMON_CI_TASKS: "v2.5.0"
    
    # renovate: datasource=npm depName=semantic-release versioning=npm
    SEMANTIC_RELEASE_VERSION: "23.0.8"
    # renovate: datasource=npm depName=@semantic-release/commit-analyzer versioning=npm
    SEMANTIC_COMMIT_ANALYZER_VERSION: "12.0.0"
    # renovate: datasource=npm depName=@semantic-release/release-notes-generator versioning=npm
    SEMANTIC_RELEASE_NOTES_GENERATOR_VERSION: "13.0.0"
    # renovate: datasource=npm depName=conventional-changelog-conventionalcommits versioning=npm
    CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION: "7.0.2"
    # renovate: datasource=npm depName=@semantic-release/gitlab versioning=npm
    SEMANTIC_RELEASE_GITLAB_VERSION: "13.0.3"
